### ISSUE TITLE
Reduce size by organisation ?

### ISSUE THREAD

**Issue by borrougagnou** [poiyomi/PoiyomiToonShader#13]
Hello !

Is it possible for you to reorganize the folder ?
Or explain somewhere (like wiki) the hierarchy ?

Because I looking for how to reduce size of my folder, so precisely how to not import all unusefull thing.

Thank you in advance :)

**Comment by poiyomi** [comment]
You can delete the samples and the textures if you're not using them that's about it.

**Comment by borrougagnou** [comment]
ho :/
okay !
thx
