### ISSUE TITLE
Lighting settings seem to mess up when applied to face and body 

### ISSUE THREAD

**Issue by SOELexicon** [poiyomi/PoiyomiToonShader#14]
so i used this shader on a few models and in some worlds the shaders lighting model actually ruins the model shading.

other shaders do not have this issue. example below
![unknown](https://user-images.githubusercontent.com/4205001/70866913-3e90f000-1f67-11ea-9c73-ac4225459ac7.png)

when compared to other shaders such as netris mmd shader it doesn't have this issue
![image](https://user-images.githubusercontent.com/4205001/70866922-59fbfb00-1f67-11ea-87c3-9539d867a9e0.png)

both shaders have identical settings. and the blend file has 0 issues with flipped normals and the face isnt a seperate mesh either.

**Comment by poiyomi** [comment]
If it's two different objects the point they sample light at will be different and have different results. To get around this either merge them or in the skinned mesh renderer settings drag your spine bone into the lighting anchor slot to force sample position. 

Let me know if this solves it for you so I can close this.

**Comment by SOELexicon** [comment]
its weird because it is 1 skinned mesh all merged so i guess blender does something weird here
![image](https://user-images.githubusercontent.com/4205001/70871520-b24af100-1f97-11ea-94fc-7dc86814a980.png)

ill close this myself because as you said dragging the spine to the lighting anchor point  fixed this and this is something i didnt know 

https://twitter.com/poiyomi/status/1206348684922937345
