### ISSUE TITLE
no how to install

### ISSUE THREAD

**Issue by Tobias0404** [poiyomi/PoiyomiToonShader#15]
Hello,

I found a vrchat avatar I wanted to use but in his discription it said I needed poishaders so I downloaded this. I watched a tutorial on how to use unity to import a avatar to vrchat but it only showed me how to import unity packages and I could not find a tutorial on how to import this. My isseu is the lack of a read me file with explaination on how to use this for the not regular users of unity like me.

**Comment by poiyomi** [comment]
Unity packages are available on the release page.

![image](https://user-images.githubusercontent.com/8877018/78086991-97a55800-738d-11ea-99a1-5def81a982ec.png)
