### ISSUE TITLE
v5.5.5 multiple error when I importing the unitypackage

### ISSUE THREAD

**Issue by borrougagnou** [poiyomi/PoiyomiToonShader#17]
Hello !

I create a new Unity Projet and insert Poiyomi at first
but....

I directly obtain all of this error... :
![image](https://user-images.githubusercontent.com/10796546/83343035-dd32c280-a2f5-11ea-86c3-f590d7a446a4.png)

If you can fix that, I wont refuse ^^

Regards.

**Comment by poiyomi** [comment]
That's the localization features currently being worked on. The errors shouldn't cause problems in any way and should go away entirely in the near future.
