### ISSUE TITLE
Build error on case-sensitive file systems due to misspelled inclusion

### ISSUE THREAD

**Issue by inertial-mass** [poiyomi/PoiyomiToonShader#20]
Hi,

on case-sensitive file systems (e.g. ext4), the spelling of CGI_PoiRimlighting.cginc in https://github.com/poiyomi/PoiyomiToonShader/blob/97b259c71e2fe694d3cb5fe26f80751cacce2c96/_PoiyomiShaders/Shaders/Includes/CGI_PoiPass.cginc#L210
causes the build to fail with

> Shader error in '.poiyomi/Toon/Advanced/Outlines Cutout': failed to open source file: 'CGI_PoiRimlighting.cginc' at Assets/_PoiyomiShaders/Shaders/Includes/CGI_PoiPass.cginc(210) (on glcore)
> Shader error in '.poiyomi/Toon/Advanced/Outlines Transparent': failed to open source file: 'CGI_PoiRimlighting.cginc' at Assets/_PoiyomiShaders/Shaders/Includes/CGI_PoiPass.cginc(210) (on glcore)
because the name of the included file is actually spelld with a capital L (CGI_PoiRimLighting.cginc).

This issue typically does not show up on Windows, as the default for NTFS is to be case-insensitive, however other OSes such as Linux, which commonly use case-sensitive file systems by default, are more likely to be affected.

Best,

inertial

**Comment by poiyomi** [comment]
This has been fixed on the internal/patreon build already and I'll close this once that build has been made public.
