### ISSUE TITLE
C# 4.0 inclusion?

### ISSUE THREAD

**Issue by MEESTERSoupCan** [poiyomi/PoiyomiToonShader#21]
I have no idea what all this stuff means, but all I get it this

Assets/_PoiyomiShaders/Scripts/ThryEditor/Editor/VRCInterface.cs(212,20): error CS1644: Feature `asynchronous functions' cannot be used because it is not part of the C# 4.0 language specification

it does not let me run the simulation because of this, and I have no idea where it stems from.

**Comment by poiyomi** [comment]
![image](https://user-images.githubusercontent.com/8877018/107905783-891c4c80-6f1d-11eb-9ac2-752991dec5e6.png)
