### ISSUE TITLE
Shader is going to "Failed to compile" category

### ISSUE THREAD

**Issue by chrisrichardz** [poiyomi/PoiyomiToonShader#25]
Shader is going to "Failed to compile" category in 2019.4.16f version. At least it works, and did not give errors. It's suppose to work like this?
Im using it not for VRChat
![Screenshot 2021-10-04 194232](https://user-images.githubusercontent.com/27918724/135891161-d59f9ae4-f9b8-4290-96f4-252628444141.png)

**Comment by poiyomi** [comment]
Have you looked at the compilation errors? Feel free to join the discord for help. https://poiyomi.com
