### ISSUE TITLE
Locking in shaders issue

### ISSUE THREAD

**Issue by Nslabinski** [poiyomi/PoiyomiToonShader#27]
Locking in shaders with two skinned mesh renderers that are slightly layered and have different textures to show the texture that shouldn't be seen. On the avatar I'm making, I have legs, then stockings, the legs have the skin texture and stockings a red texture,  when the shader on the legs are unlocked the red texture is seen, but when locking, the skin texture is seen, and even switching the textures around cause the same thing, which would make sense because the stockings cover the legs

**Comment by poiyomi** [comment]
Join the discord for technical help. [DISCORD](https://poiyomi.com)
