### ISSUE TITLE
[Question] MMD Models

### ISSUE THREAD

**Issue by Legoman99573** [poiyomi/PoiyomiToonShader#3]
I am wondering when importing an MMD Model using your shader, where would be the best place to place sphere textures at to make it more detailed?

I was asking as i am not sure if the shader does the same as https://github.com/DarthShader/Flat-Lit-Toon-MMD-Extension where it supports sphere textures to make it more detailed.

**Comment by poiyomi** [comment]
Matcap / Sphere textures are planned for 2.3.0

**Comment by Legoman99573** [comment]
Thank you. This will make MMD Models look more detailed and not a fan of flat lit toon as much since i dont see development going anywhere recently since the last update was September 29th, 2018.
