### ISSUE TITLE
Shader locking breaks with Japanese characters

### ISSUE THREAD

**Issue by Hokome** [poiyomi/PoiyomiToonShader#31]
Unity 2019.4.31f1
Poiyomi 7.3.046

Steps:
- Import a material with Japanese (or possibly other foreign) characters in its name.
- Tick a property to get the **red** clock.
- Lock the shader

You will get an error and the locking will cancel

**Comment by rrazgriz** [comment]
This has been fixed for a few months - when locking, ThryEditor now gracefully turns names with non-ASCII characters into something ASCII compatible.
