### ISSUE TITLE
Display issues on Mac Unity clients (Metal)

### ISSUE THREAD

**Issue by Casuallynoted** [poiyomi/PoiyomiToonShader#33]
Getting errors like this when trying to view the toon shader on a Mac install of Unity, running via Metal.

Shader error in '.poiyomi/• Poiyomi Toon •': failed to open source file: 'CGI_PoiPenetration.cginc' at Assets/rascalRabbit_update3/3D+2D_assets/poiyomiShaders/Shaders/Pro/Includes/CGI_PoiPass.cginc(99) (on metal)

Compiling Vertex program with UNITY_PASS_FORWARDBASE DIRECTIONAL LIGHTPROBE_SH _EMISSION VIGNETTE_MASKED VIGNETTE_CLASSIC _SPECGLOSSMAP _TERRAIN_NORMAL_MAP FINALPASS
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

**Comment by poiyomi** [comment]
yeah metal doesn't support all the features in the shader and it therefore does not run on it sadly.
