### ISSUE TITLE
Emissions Stop Working

### ISSUE THREAD

**Issue by xxVinWestley** [poiyomi/PoiyomiToonShader#34]
Made an avatar with glowing emissions, uploaded it for PC, switched shaders to Standard Lite with emissions enabled for quest. When I switched back to Poiyomi to update the PC version, the emissions no longer work.

**Comment by Docteh** [comment]
Did you make separate materials, or are you manually changing the existing material to switch back and forth?

**Comment by rrazgriz** [comment]
Closed due to age. Feel free to ask questions in our discord at http://discord.gg/poiyomi!
