### ISSUE TITLE
Shader Optimizer requires VRChat SDK to be present

### ISSUE THREAD

**Issue by geoid-dev** [poiyomi/PoiyomiToonShader#35]
Discovered that not having the VRChat SDK present in your project seems to cause 11 errors to show up - see below for more information; 

![image](https://user-images.githubusercontent.com/107812945/182003619-78ea15eb-8dee-4d8e-97ce-552554ac042a.png)

After installing the VRChat SDK these issues go away. I intend to use this project entirely for CVR work, so ideally not having the VRChat SDK present is best.

What's present in my project:
ABI CCK
Dynamic Bone
Karin (booth.pm avatar, no shaders or scripts)

**Comment by poiyomi** [comment]
This is not the case. When VRC is placed in a project it add defines to said project. which tells everything it exists. you probably removed VRCSDK and didn't remove the defines. 

File -> Build Settings -> Player Settings -> Remove the VRC SDK from this text
