### ISSUE TITLE
Rim lighting breaks and turns "greenish"

### ISSUE THREAD

**Issue by endjui** [poiyomi/PoiyomiToonShader#36]
Rim lighting randomly breaks and stops working. Re-importing the package did not help.

See image for reference.
![image](https://user-images.githubusercontent.com/45940015/186674310-13de46cb-7bdc-42d8-a982-6892f8e8324c.png)

**Comment by rrazgriz** [comment]
This has been fixed as of 8.1.156. The old behavior (caused by a clamp) can be replicated by enabling "Clamp Intensity" for rim lighting, which defaults to off.
