### ISSUE TITLE
Seeing Double's

### ISSUE THREAD

**Issue by CrescentNightmare** [poiyomi/PoiyomiToonShader#4]
Sometimes when i upload an avatar for no reason at all vr users will see double of me and i will see double of me if im in vr but for desktop users it will be fine. any help would be nice.

**Comment by poiyomi** [comment]
Sometimes on import unity fails to compile the shader for 1 eye. Try deleting the shader and reimporting.

**Comment by CrescentNightmare** [comment]
It seems to be based on world

**Comment by CrescentNightmare** [comment]
My fiance lazorithe is streaming right now if you need proof

**Comment by CrescentNightmare** [comment]
Plus it happens every time im import the shader so i doubt its a failed import

**Comment by poiyomi** [comment]
I've solved this with reimporting before, it's happened to many people. If you haven't please try to delete the shader and reimport. I'm not home atm but feel free to join the discord and talk to others who have had the same issues.

Send me the name of the world and I'll check it out.

**Comment by CrescentNightmare** [comment]
Cards Against Humanity VR Is the current world causing the issue

**Comment by poiyomi** [comment]
![20190321153108_1_vr](https://user-images.githubusercontent.com/8877018/54780228-96c0de80-4bef-11e9-9eb4-f06ce0cb2c95.jpg)
![20190321153547_1_vr](https://user-images.githubusercontent.com/8877018/54780229-96c0de80-4bef-11e9-985e-abc5be21ccb8.jpg)
After testing in multiple worlds on a vive I did not see doubling. please try deleting, reimporting and getting back to me with the results.

**Comment by poiyomi** [comment]
Resolved by reimporting over and over until unity decided to compile it correctly
