### ISSUE TITLE
Poiyomi's shader optimization breaks other shaders

### ISSUE THREAD

**Issue by whiteflare** [poiyomi/PoiyomiToonShader#43]
https://github.com/poiyomi/PoiyomiToonShader/blob/96ded0fbcda2a801de97c6ab277b6013282ec9fd/_PoiyomiShaders/Scripts/ThryEditor/Editor/ShaderOptimizer.cs#L1999

This implementation seems to break other shaders that are not Poiyomi shader.
ACLS shader falls into this problem and is removed because it has the `_ShaderOptimizerEnabled` property but not the name `Hidden/Locked/`.

Adding the following branch just before solves the problem.
```
if (!shader.name.Contains("Poiyomi"))
    return;
```

**Comment by rrazgriz** [comment]
Thanks, we're working on improving false positives with unlocked shader stripping.

ThryEditor is *technically* general-purpose so we don't want to hard-code Poiyomi into it. I think it should be okay if we also check for `shader_is_using_thry_editor`, should narrow it down.

**Comment by rrazgriz** [comment]
I've made a change that should prevent this: https://github.com/Thryrallo/ThryEditor/commit/e51a98565d66bc32617f751d434b074d9f324013. This change will make it into the next Poiyomi build.

**Comment by rrazgriz** [comment]
This should be fixed in the latest build, feel free to reopen if you find further false positives.
