### ISSUE TITLE
[8.1.167] Consistent Unity 2022 crash on MacOS when attempting to lock shaders

### ISSUE THREAD

**Issue by venusyprime** [poiyomi/PoiyomiToonShader#56]
I'm testing out a new project on Unity 2022 to make sure everything is ready for when VRChat forces the upgrade.

After installing Poiyomi via vpm, it appears to be consistently crashing when attempting to lock - whether manually or automatically when trying to upload.

The same thing happens with an older project upgraded to 8.1.167 and Unity 2022.

MacOS version: 14.1.2

Wasn't sure what logs are needed.

[shadercompiler-AssetImportWorker0.log](https://github.com/poiyomi/PoiyomiToonShader/files/13819450/shadercompiler-AssetImportWorker0.log)
[shadercompiler-UnityShaderCompiler0.log](https://github.com/poiyomi/PoiyomiToonShader/files/13819456/shadercompiler-UnityShaderCompiler0.log)
[shadercompiler-UnityShaderCompiler1.log](https://github.com/poiyomi/PoiyomiToonShader/files/13819453/shadercompiler-UnityShaderCompiler1.log)
[shadercompiler-UnityShaderCompiler2.log](https://github.com/poiyomi/PoiyomiToonShader/files/13819452/shadercompiler-UnityShaderCompiler2.log)
[shadercompiler-UnityShaderCompiler3.log](https://github.com/poiyomi/PoiyomiToonShader/files/13819455/shadercompiler-UnityShaderCompiler3.log)
[shadercompiler-UnityShaderCompiler4.log](https://github.com/poiyomi/PoiyomiToonShader/files/13819451/shadercompiler-UnityShaderCompiler4.log)
[shadercompiler-UnityShaderCompiler5.log](https://github.com/poiyomi/PoiyomiToonShader/files/13819454/shadercompiler-UnityShaderCompiler5.log)
[shadercompiler-UnityShaderCompiler6.log](https://github.com/poiyomi/PoiyomiToonShader/files/13819457/shadercompiler-UnityShaderCompiler6.log)

**Comment by poiyomi** [comment]
Sadly the shader isn't properly functional on macs and there are no plans to fully support mac.
