### ISSUE TITLE
Way to disable lock feature?

### ISSUE THREAD

**Issue by red1134** [poiyomi/PoiyomiToonShader#59]
I need to disable this feature because it refuses to lock the shader on one material, resulting in it being pink. I don't care about performance I just want to upload it anyways with the unlocked material. Why can't you give this option?

**Comment by poiyomi** [comment]
Because the performance of an unlocked material can be 100x worse than locked (no exaggeration). If your material turns pink when locking in consider updating to a newer version where the problem has been fixed.
