### ISSUE TITLE
Add a version similar to Mochie's Screen FX to Poiyomi.

### ISSUE THREAD

**Issue by AraHaan** [poiyomi/PoiyomiToonShader#66]
I have a little issue where I am trying to optimize a system that uses multiple GameObjects with Materials using Mochie's Screen FX shader.

However, I noticed that this particular shader is not scale friendly I believe and would like a Poiyomi version that is scale friendly.

This is because the only difference between each of those materials is the changed Min and Max ranges, and if Poiyomi could make it possible to have it read the game object's scale and to calculate this value dynamically I would be happy as it could then start out with a single FIXED value, a single game object, and single material for a depth effect (for example like if you got a slime avatar and want a shader to provide an effect for walking inside of said slime avatar).

This is one of the things blocking me from my VRChat avatar significantly as a particular system has 7 of these game objects with materials using said shader.

Thanks in advance and let me know if such a thing is possible.

**Comment by slord399** [comment]
If you want to do feature request, join off our discord at "discord.gg/poiyomi" and post to [feature-request channel](https://canary.discord.com/channels/550477546958094348/553319525387599910).

*This issue may not checked frequently by maintainer.

**Comment by poiyomi** [comment]
I will close this as what Slord said is the correct place for feature requests, but I'll leave a note. 

If you're scaling your avatar the scale value is available via animation parameters. There isn't a way to just include scale in the shader however you can create scale animations which scales those minmax numbers in whatever way you want via the scale parameter.
