### ISSUE TITLE
Make front more like original murdoc, as shapekey and swap basis

### ISSUE THREAD

**Issue by skullyhellfire** [poiyomi/PoiyomiToonShader#67]
Make front more like original murdoc, as shapekey and swap basis, use m1 as ref

Change eyes to be more half circles, and make snout slightly narrower

<img width="752" alt="Screenshot 2024-10-09 040140" src="https://github.com/user-attachments/assets/15fdc943-c298-41af-a869-50ea14ccf8c4">
<img width="1262" alt="Screenshot 2024-10-09 041234" src="https://github.com/user-attachments/assets/17d33f96-058a-4aa0-984c-f2b18d3ed59e">

Keep side profile more towards m2

![image](https://github.com/user-attachments/assets/14dd220b-7092-4b8b-ad11-abf59ba0ecbc)
![image](https://github.com/user-attachments/assets/4ad46c6e-5a9a-4638-98b1-c89887fd980a)

Here I think m2 looks better on eyes and shape

**Comment by skullyhellfire** [comment]
can always transfer the shape to the current fbx later if modifying on old fbx

**Comment by rurre** [comment]
I think you got the wrong repo buddy
